name: CI
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  check-format:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm i

      - name: Check format
        run: npm run check:format

      # - name: Cypress run
      #   uses: cypress-io/github-action@v6
      #   with:
      #     build: pnpm build
      #     start: pnpm preview
      #   env:
      #     PUBLIC_API_URL: ${{secrets.PUBLIC_API_URL}}
      #     PUBLIC_SUPABASE_KEY: ${{secrets.PUBLIC_SUPABASE_KEY}}
      #     PUBLIC_SUPABASE_URL: ${{secrets.PUBLIC_SUPABASE_URL}}
